FORMAT: 1A
HOST: https://api.jumplead.com/v1

# Jumplead
Welcome to the Jumplead Legacy API v1 developer documentation! 

This API is deprecated and will soon be retired in favour of our v2 API.

## Authentication

The Jumplead API uses Personal access tokens (API Keys) for authentication. You will find your personal access tokens in your [Account Settings](https://app.jumplead.com/settings/access-tokens). 

Once you have your api key it'll need to be included in the `X-Jumplead-Auth` header for all requests.

## Responses
All responses from the Jumplead API are wrapped inside a "data" namespace at the top level of the JSON response. The top level also includes a "meta" namespace which includes extra information to aid the developer.

### Paging
All Collections from the Jumplead API are paged in batches of 20 results. This limit is currently hard-coded and can't be changed. Some endpoints don't having paging restrictions.

Information about paging is contained inside the "meta"."pagination" namespace. It's contents are self explanatory.

### Embedded Records
Some records contain links to other resources. For example a contact is assigned a company. 

When resources can be embedded there will be an "availableIncludes" includes namespace inside the meta information. You can then tell the API to include the resources by passing them as a GET variable. For example `?include=company` or including multiple resources `?include=company,geoname`. Some resources such as contacts include these resources by default.

# Group Automations
Automations are a series of actions that can be applied to a contact.

## Automation Fields
| Name              | Description                               | Details           |
| ----------------- | ----------------------------------------- | ----------------- |
| name              | The name of the Automation                | string, required  |
| description       | A friendly description of the Automation  | string, required  |
| trigger_type      | The type of the automation trigger        | string, optional  |
| trigger_id        | The ID of the trigger, see trigger_type   | mixed, optional   |
| actions           | An array of actions for the automation    | array, optional   |
| stats             | System generated statistics               | object, read-only |

## Automation Collection [/automations{?trigger_type}]

### List all Automations [GET]
+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey

+ Response 200 (application/json)

    + Body
    
            {
              "data": [
                {
                  "id": "5086bffb7558f4b37a000000",
                  "name": "No Sub - 21 Days",
                  "description": "Triggered when client hasnt subscribed after 21 days of taking a trial",
                  "trigger_type": "api",
                  "trigger_id": null,
                  "actions": [
                    
                  ],
                  "stats": {
                    "conversion": 2,
                    "conversion_rate": 0.058258083309059
                  }
                },
                {
                  "id": "5097ee7241d906ef07000000",
                  "name": "Contact Form",
                  "description": "Jumplead website contact form",
                  "trigger_type": "form",
                  "trigger_id": "502901e341d906880800000b",
                  "actions": [
                    {
                      "type": "notification",
                      "users": [
                        1,
                        2,
                        1074
                      ]
                    },
                    {
                      "type": "stage",
                      "id": 55
                    }
                  ],
                  "stats": {
                    "conversion": 11,
                    "conversion_rate": 0.32041945819983
                  }
                }
              ],
              "meta": {
                "pagination": {
                  "total": 16,
                  "count": 10,
                  "per_page": 2,
                  "current_page": 1,
                  "total_pages": 2,
                  "links": {
                    "next": "https:\/\/app.jumplead.com\/api\/v1\/automations?page=2"
                  }
                }
              }
            }

+ Parameters
    + trigger_type (optional, string) ... Filter automations by their trigger type.

## Automation [/automations/{id}]

+ Parameters
    + id (required, string, `5086bfdb75d8f4b37a000000`) ... The ID of the automation.
    
+ Model (application/json)

    + Body
    
            {
              "data": {
                "id": "5086bfdb75d8f4b37a000000",
                "name": "Contact Form",
                "description": "Trigger when a contact submits the contact form",
                "trigger_type": "api",
                "trigger_id": null,
                "actions": [
                  
                ],
                "stats": {
                  "conversion": 2,
                  "conversion_rate": 0.058258083309059
                }
              }
            }

### Retrieve an Automation [GET]
+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey

+ Response 200 (application/json)

    [Automation][]

## Automation Trigger [/automations/trigger]

### Trigger an Automation [POST]
To trigger an Automation you MUST pass an **automation_id** and either a **contact_id** or a **first_name**, **last_name** and an **email**.

If the contact doesn't exist Jumplead will create one automatically and trigger the automation against the contact.

+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey

    + Body

            {
              {
                "automation_id": "5086bfdb75d8f4b37a000000",
                "first_name": "John",
                "last_name": "Smith",
                "email": "john.smith@gmail.com"
              }
            }

+ Response 202

    + Body
    
            Automation triggered.


# Group Contacts

## Contact Fields
| Name              | Description                                                                                                                               | Details                                               |
| ----------------- | ----------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| first_name        | The first name of the contact                                                                                                             | string, required                                      |
| last_name         | The last name of the contact                                                                                                              | string, required                                      |
| email             | Email address for the contact. Must be valid                                                                                              | string, required                                      |
| contactable       | Flag for if the contact has globally opted out of emails                                                                                  | boolean, optional                                     |
| contact_company   | The ID of the company this contact belongs to                                                                                             | string, optional                                      |
| background        | A textual description of the contact                                                                                                      | string, optional                                      |
| status            | Status for the contact                                                                                                                    | integer, optional<br>0 = Not Managed<br>1 = Managed   |
| stage             | ID of the Stage for the contact. Fetch stage IDs from the Stages endpoint                                                                 | integer, optional                                     |
| tags              | A list of any tags applied to the contact                                                                                                 | array, optional                                       |
| lead_score        | The contact's [lead score](http://help.jumplead.com/pages/explore/contacts/lead-scores/) generated by the system                          | integer, read-only                                    |
| geoname           | Jumplead uses [Geonames](http://www.geonames.org/) to identify a Contact's location. This ID is the GeonameID of the contact's location   | integer, optional                                     |

## Contacts Collection [/contacts{?email,name,stage_id,list_id,filterLetter,filterTag,filterScore,opted,hard_bounced}]

### List all Contacts [GET]
+ Parameters
    + email (optional, string, `jane.doe@gmail.com`) ... Filter contacts by email address.
    + name (optional, string, `Jane Doe`) ... Search for contacts by their name
    + stage_id (optional, integer, `1`) ... Filter contacts by a stage
    + list_id (optional, integer, `1`) ... Filter contacts by a contact list
    + filterLetter (optional, string, `A`) ... Search for contacts beginning with a letter
    + filterTag (optional, string, `marketing`) ... Search for contacts that have a specific tag
    + filterScore (optional, string)
        Filter contacts by lead score
        + Values
            + `red-hot`
            + `hot`
            + `warm`
            + `cool`
    + opted = `IN` (optional, string)
        Filter contacts by whether they are opted in to campaigns
        + Values
            + `IN`
            + `OUT`
    + hard_bounced = `true` (optional, boolean)
        Filter contacts by whether their email address has hard bounced during a campaign
        + Values
            + `true`
            + `false`
    
+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey

+ Response 200 (application/json)

    + Body
    
            {
              "data": [
                {
                  "id": "53babf8c7558f4e3358b456a",
                  "first_name": "Paul",
                  "last_name": "Smith",
                  "contact_company": "53babf8c7558f4e3358b4569",
                  "background": "Some useful background information",
                  "status": 1,
                  "stage": 55,
                  "email": "paul.smith@gmail.com",
                  "contactable": true,
                  "tags": [
                    "some",
                    "random",
                    "tags"
                  ],
                  "lead_score": 50,
                  "geoname": 3333165,
                  "custom_field_data": [
                    
                  ]
                },
                {
                  "id": "53babf8c7333f4e3358b222a",
                  "first_name": "Joe",
                  "last_name": "Bloggs",
                  "contact_company": "53babf8c7558f4e3358b4569",
                  "background": "Some useful background information",
                  "status": 1,
                  "stage": 55,
                  "email": "joe.bloggs@yahoo.com",
                  "contactable": false,
                  "tags": [
                    "random",
                    "tags"
                  ],
                  "lead_score": 10,
                  "geoname": 3333165,
                  "custom_field_data": [
                    
                  ]
                }
              ],
              "meta": {
                "availableIncludes": [
                  "geoname",
                  "company"
                ],
                "pagination": {
                  "total": 1297,
                  "count": 2,
                  "per_page": 2,
                  "current_page": 1,
                  "total_pages": 65,
                  "links": {
                    "next": "https:\/\/app.jumplead.com\/api\/v1\/contacts?page=2"
                  }
                }
              }
            }
            

## Create a Contact [/contacts]
### Create a Contact [POST]
+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey
            
    + Body
    
            {
              "data": {
                  "first_name": "Joe",
                  "last_name": "Bloggs",
                  "email": "joe.bloggs@yahoo.com"
              }
            }

+ Response 200 (application/json)

    + Body
    
            {
              "data": {
                  "id": "53babf8c7333f4e3358b222a",
                  "first_name": "Joe",
                  "last_name": "Bloggs",
                  "contact_company": "53babf8c7558f4e3358b4569",
                  "background": "Some useful background information",
                  "status": 1,
                  "stage": 55,
                  "email": "joe.bloggs@yahoo.com",
                  "contactable": false,
                  "tags": [
                    "random",
                    "tags"
                  ],
                  "lead_score": 10,
                  "geoname": 3333165,
                  "custom_field_data": [
                    
                  ]
              }
            }
            
## Contact [/contacts/{id}]

+ Parameters
    + id (required, string, `5086bfdb75d8f4b37a000000`) ... The ID of the contact.
    
+ Model (application/json)

    + Body
    
            {
              "data": {
                  "id": "53babf8c7333f4e3358b222a",
                  "first_name": "Joe",
                  "last_name": "Bloggs",
                  "contact_company": "53babf8c7558f4e3358b4569",
                  "background": "Some useful background information",
                  "status": 1,
                  "stage": 55,
                  "email": "joe.bloggs@yahoo.com",
                  "contactable": false,
                  "tags": [
                    "random",
                    "tags"
                  ],
                  "lead_score": 10,
                  "geoname": 3333165,
                  "custom_field_data": [
                    
                  ]
              }
            }
            
### Retrieve a Contact [GET]
+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey

+ Response 200 (application/json)

    [Contact][]
    
### Update a Contact [PUT]
+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey
            
            
    + Body
    
            {
              "data": {
                  "email": "joe.bloggs@yahoo.com"
              }
            }

+ Response 200 (application/json)

    [Contact][]
    
# Group Contact Companies
Use contact companies to group contacts under a company.

## Contact Company Fields
| Name                   | Description                                                           | Details                 |
| ---------------------- | --------------------------------------------------------------------- | ----------------------- |
| name                   | The name of the contact company                                       | string, required        |
| description            | Description of the company                                            | string, optional        |
| logo_url               | The URL of the company logo                                           | string, optional        |
| social                 | System field used by Jumplead App                                     | array, read-only        |
| tags                   | An array of tags to use for the company                               | array[string], optional |
| geoname                | Jumplead uses [Geonames](http://www.geonames.org/) for locations      | integer, optional       |
| website                | The Website address of the company                                    | string, optional        |
| address_street_address | The street address of the company                                     | string, optional        |
| address_locality       | The Town / City of the company                                        | string, optional        |
| address_admin_area     | The State / Province of the company                                   | string, optional        |
| address_postal_code    | The ZIP / Postcode of the company                                     | string, optional        |
| address_country        | ISO 2 Digit Country code for the company                              | string, optional        |

## Contact Companies Collection [/contactCompanies{?name}]

### List all Contact Companies [GET]
+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey

+ Response 200 (application/json)

    + Body
    
            {
              "data": [
                {
                    "id": "55d1bfcd463a6701008b45aa",
                    "name": "Jumplead",
                    "description": "",
                    "logo_url": "https://d2ojpxxtu63wzl.cloudfront.net/static/0a00b78d8f220c4263afe60fdc0254f0_280fb85f2a470312010c85b3f3482d49f777ffa95d37db5ba3401f687adc414b",
                    "social": [],
                    "tags": ['jumplead'],
                    "geoname": 2639076,
                    "website": "https://jumplead.com",
                    "address_street_address": "23 Hallfields Lane Rothley",
                    "address_locality": "Leicester",
                    "address_admin_area": "Leicestershire",
                    "address_postal_code": "LE7 7NF",
                    "address_country": "GB"
                }
              ],
              "meta": {
                "pagination": {
                  "total": 1,
                  "count": 1,
                  "per_page": 20,
                  "current_page": 1,
                  "total_pages": 1,
                  "links": [
                    
                  ]
                }
              }
            }
            
## Create a Contact Company [/contactCompanies]
### Create a Contact Company [POST]
+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey
            
    + Body
    
            {
                "data": {
                    "name": "Jumplead",
                    "description": "My awesome new company!"
                }
            }

+ Response 200 (application/json)

    + Body
    
            {
              "data": {
                    "id": "55d1bfcd463a6701008b45aa",
                    "name": "Jumplead",
                    "description": "My awesome new company!",
                    "logo_url": null,
                    "social": [],
                    "tags": [],
                    "geoname": null,
                    "website": null,
                    "address_street_address": null,
                    "address_locality": null,
                    "address_admin_area": null,
                    "address_postal_code": null,
                    "address_country": null
              }
            }
        
## Contact Company [/contactCompanies/{id}]

+ Parameters
    + id (required, string, `55d1bfcd463a6701008b45aa`) ... The ID of the contact company.
    
+ Model (application/json)

    + Body
    
            {
                "data": {
                    "id": "55d1bfcd463a6701008b45aa",
                    "name": "Jumplead",
                    "description": "",
                    "logo_url": "https://d2ojpxxtu63wzl.cloudfront.net/static/0a00b78d8f220c4263afe60fdc0254f0_280fb85f2a470312010c85b3f3482d49f777ffa95d37db5ba3401f687adc414b",
                    "social": [],
                    "tags": ['jumplead'],
                    "geoname": 2639076,
                    "website": "https://jumplead.com",
                    "address_street_address": "23 Hallfields Lane Rothley",
                    "address_locality": "Leicester",
                    "address_admin_area": "Leicestershire",
                    "address_postal_code": "LE7 7NF",
                    "address_country": "GB"
                }
            }
            
### Retrieve a Contact Company [GET]
+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey

+ Response 200 (application/json)

    [Contact Company][]
    
### Update a Contact Company [PUT]
+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey
            
            
    + Body
    
            {
              "data": {
                  "name": "Jumplead Ltd"
              }
            }

+ Response 200 (application/json)

    [Contact Company][]
    
# Group Stages
Stages are used to group contacts.

## Stage Fields
| Name              | Description                                                                   | Details               |
| ----------------- | ----------------------------------------------------------------------------- | --------------------- |
| name              | The name of the stage                                                         | string, required      |
| parent_id         | System field used by Jumplead App                                             | string, optional      |
| order             | System field used by Jumplead App                                             | integer, optional     |
| hidden            | System field used by Jumplead App                                             | boolean, optional     |
| total_contacts    | System generated statistic with the total number of contacts in the stage     | integer, read-only    |

## Stages Collection [/stages]

### List all Stages [GET]
+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey

+ Response 200 (application/json)

    + Body
    
            {
              "data": [
                {
                  "id": 1,
                  "name": "Stage 1",
                  "parent_id": null,
                  "order": 1,
                  "hidden": false,
                  "total_contacts": 23
                },
                {
                  "id": 2,
                  "name": "Stage 2",
                  "parent_id": null,
                  "order": 2,
                  "hidden": false,
                  "total_contacts": 56
                }
              ],
              "meta": {
                "pagination": {
                  "total": 2,
                  "count": 2,
                  "per_page": 9999,
                  "current_page": 1,
                  "total_pages": 1,
                  "links": [
                    
                  ]
                }
              }
            }
            
## Stage [/stages/{id}]

+ Parameters
    + id (required, integer, `2`) ... The ID of the stage.
    
+ Model (application/json)

    + Body
    
            {
              "data": {
                  "id": 2,
                  "name": "Stage 2",
                  "parent_id": null,
                  "order": 2,
                  "hidden": false,
                  "total_contacts": 56
              }
            }
            
### Retrieve a Stage [GET]
+ Request (application/json)

    + Headers
    
            X-Jumplead-Auth: myApiKey

+ Response 200 (application/json)

    [Stage][]