FORMAT: 1A
HOST: https://app.jumplead.com/api/v1

# Jumplead
Welcome to the Jumpelead API v1 developer documentation!

## Authentication

![OAuth 2.0](http://oauth.net/images/oauth-2-sm.png)

The Jumplead API uses [OAuth 2.0](http://oauth.net/2/) for authentication. You will first need to register your application on the [Jumplead Developers](http://developers.jumplead.com) site.

Once registered use the following endpoints to get your Access and Refresh tokens:

* `Authorization URL` https://account.mooloop.com/oauth/authorize
* `Access Token URL` https://account.mooloop.com/oauth/access_token
* `Refresh Token URL` https://account.mooloop.com/oauth/access_token

### Scopes

The following scopes are available. Only request the scopes that you need access to.

| Scope                         | Description                                                   |
| ----------------------------- | ------------------------------------------------------------- |
| jumplead.personal             | Access to personal information, such as email and address.    |
| jumplead.automation           | Access to manage Automations                                  |
| jumplead.streams              | Access to manage Activity Streams                             |
| jumplead.landing-pages        | Access to manage Landing Pages                                |
| jumplead.lead-capture-forms   | Access to manage Lead capture forms                           |
| jumplead.campaigns            | Access to manage Campaigns                                    |
| jumplead.contacts             | Access to manage Contacts                                     |
| jumplead.messages             | Access to manage Messages                                     |
| jumplead.analytics            | Access to Analytics Statistics                                |
| jumplead.reseller             | Access to Reseller Controls                                   |
| jumplead.billing              | Access to Billing Information and Invoices                    |
| jumplead.keywords             | Access to SERP Keywords                                       |


# Group Automations
Automations are a series of actions that can be applied to a contact.

## Automation Collection [/automations{?trigger_type}]

### List all Automations [GET]
+ Response 200 (application/json)

        {
          "data": [
            {
              "id": "5086bffb7558f4b37a000000",
              "name": "No Sub - 21 Days",
              "description": "Triggered when client hasnt subscribed after 21 days of taking a trial",
              "trigger_type": "api",
              "trigger_id": null,
              "actions": [
                
              ],
              "stats": {
                "conversion": 2,
                "conversion_rate": 0.058258083309059
              }
            },
            {
              "id": "5097ee7241d906ef07000000",
              "name": "Contact Form",
              "description": "Jumplead website contact form",
              "trigger_type": "form",
              "trigger_id": "502901e341d906880800000b",
              "actions": [
                {
                  "type": "notification",
                  "users": [
                    1,
                    2,
                    1074
                  ]
                },
                {
                  "type": "stage",
                  "id": 55
                }
              ],
              "stats": {
                "conversion": 11,
                "conversion_rate": 0.32041945819983
              }
            }
          ],
          "meta": {
            "pagination": {
              "total": 16,
              "count": 10,
              "per_page": 2,
              "current_page": 1,
              "total_pages": 2,
              "links": {
                "next": "https:\/\/app.jumplead.com\/api\/v1\/automations?page=2"
              }
            }
          }
        }

+ Parameters
    + trigger_type (optional, string) ... Filter automations by their trigger type.

### Create an Automation [POST]
+ Request (application/json)

        {
          "data": {
            "name": "Contact Form",
            "description": "Trigger when a contact submits the contact form",
          }
        }

+ Response 200 (application/json)

            {
              "data": {
                "id": "5086bfdb75d8f4b37a000000",
                "name": "Contact Form",
                "description": "Trigger when a contact submits the contact form",
                "trigger_type": "api",
                "trigger_id": null,
                "actions": [
                  
                ],
                "stats": {
                  "conversion": 0,
                  "conversion_rate": 0
                }
              }
            }

## Automation [/automations/{id}]
A single Automation object with all its details

+ Parameters
    + id (required, string, `5086bfdb75d8f4b37a000000`) ... The ID of the automation.
    
+ Model (application/json)

    + Body
    
            {
              "data": {
                "id": "5086bfdb75d8f4b37a000000",
                "name": "Contact Form",
                "description": "Trigger when a contact submits the contact form",
                "trigger_type": "api",
                "trigger_id": null,
                "actions": [
                  
                ],
                "stats": {
                  "conversion": 2,
                  "conversion_rate": 0.058258083309059
                }
              }
            }

### Retrieve an Automation [GET]
+ Response 200 (application/json)
    [Automation][]

+ Response 400 (text/plain)

        ID is not valid.

### Update an Automation [PUT]
+ Request (application/json)

        {
          "data": {
            "name": "Updated Contact Form Name"
          }
        }

+ Response 200 (application/json)
    [Automation][]

### Remove an Automation [DELETE]
+ Response 204
